notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - bsdtar
   - time
   - curl
   - libcurl4-openssl-dev
   - nettle-dev
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - unzip
   - libpng12-dev
   - libexpat1-dev

install: true

language: perl

perl:
 - "5.22"

before_script:
 - git clone --depth 1 --single-branch --branch develop https://github.com/cancerit/cgpBigWig.git
 - cd cgpBigWig
 - ./setup.sh $HOME/wtsi-opt
 - cd ../

script:
 - ./setup.sh ~/wtsi-opt
 - ~/wtsi-opt/bin/samtools view # dump usage to show intact
