notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - bsdtar
   - time
   - curl
   - libcurl4-openssl-dev
   - nettle-dev
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - unzip
   - libpng12-dev
   - libexpat1-dev

install: true

language: c # doesn't build Bio::DB::BigFile otherwise

script:
 - ./setup.sh ~/wtsi-opt
